mappings:
  RSSAggEntry: Silverstripe\RSSAggregator\RSSAggEntry
  RSSAggregatingPage: Silverstripe\RSSAggregator\RSSAggregationPage
  RSSAggregatingPage_Controller: PageController
  RSSAggSource: Silverstripe\RSSAggregator\RSSAggSource
